-- 코드를 작성해주세요
SELECT IP.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE IP
LEFT JOIN ITEM_TREE AS IC
            ON IP.ITEM_ID = IC.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO AS II
            ON IP.ITEM_ID = II.ITEM_ID
WHERE IC.ITEM_ID IS NULL
ORDER BY IP.ITEM_ID DESC