SELECT CAR_ID,
       ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION  
       # 평균 대여 기간(시작~종료일 포함) 계산 후 반올림
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID# 자동차별로 그룹화
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
        # 평균 대여 기간이 7일 이상인 자동차만 필터링
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC