-- 코드를 입력하세요
WITH TOTAL AS(
SELECT *
FROM USER_INFO
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS TOTAL_SALES,
    ROUND(
        COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(*) FROM TOTAL), 1
    ) AS RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S ON U.USER_ID=S.USER_ID
WHERE U.USER_ID IN (SELECT USER_ID FROM TOTAL)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC