WITH
-- 2021년 가입자 수
USER_2021 AS (
    SELECT
        COUNT(ui.USER_ID) AS TOTAL_USERS_2021
    FROM USER_INFO ui
    WHERE YEAR(ui.JOINED) = 2021
)
-- 집계
SELECT
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / u21.TOTAL_USERS_2021,1) AS PURCHASED_RATIO
FROM USER_INFO u
INNER JOIN ONLINE_SALE s -- 구매 이력이 있는 경우만 가져오기
    ON u.USER_ID = s.USER_ID
CROSS JOIN USER_2021 u21 -- 테이블에 2021년 가입자 수를 전부 붙여주기
WHERE YEAR(u.JOINED) = 2021 -- 2021년 행만 떼어 오기
GROUP BY
    YEAR(s.SALES_DATE),
    MONTH(s.SALES_DATE)
;