WITH MAY_ORDER_AMT AS (
    SELECT PRODUCT_ID
            ,SUM(AMOUNT) AS ORDER_AMT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID
        ,P.PRODUCT_NAME
        ,ORDER_AMT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN MAY_ORDER_AMT AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID