-- 코드를 입력하세요
SELECT
    a.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    a.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM
    APPOINTMENT a
    INNER JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
    INNER JOIN PATIENT p ON a.PT_NO = p.PT_NO
WHERE
    a.APNT_CNCL_YN = 'N'
    AND a.APNT_YMD LIKE '%2022-04-13%'
    AND a.MCDP_CD = 'CS'
ORDER BY
    a.APNT_YMD ASC;