WITH RECURSIVE hours AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1
    FROM hours
    WHERE hour < 23
)

SELECT H.hour AS HOUR,
    COUNT(a.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = H.hour
GROUP BY H.hour
ORDER BY H.hour