SELECT M.MEMBER_NAME, R.REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE M
LEFT JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE (
    SELECT COUNT(REVIEW_ID)
    FROM REST_REVIEW
    WHERE MEMBER_ID = M.MEMBER_ID
) = (
    SELECT MAX(REVIEW_COUNT)
    FROM (
        SELECT COUNT(REVIEW_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) C
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;

    
        
