SELECT G.SCORE22 AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) AS 'SCORE22'
      FROM HR_GRADE
      GROUP BY EMP_NO
      ORDER BY SCORE22 DESC
      LIMIT 1) G
LEFT JOIN HR_EMPLOYEES E
ON G.EMP_NO = E.EMP_NO;