SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (
    SELECT *,
    rank() over (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS mp
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    ) AS rnk
WHERE rnk.mp = 1
ORDER BY PRICE DESC;